## Path to your oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

export LSCOLORS='exfxcxdxbxegedabagacad'
export CLICOLOR=true

## Set name of the theme to load.
## Look in ~/.oh-my-zsh/themes/
ZSH_THEME="dracula"

## oh-my-zsh plugins
plugins=(git zsh-nvm npm git-it-on)

# User configuration

## RVM & MANPath
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
#export MANPATH="/usr/local/man:$MANPATH"

## NVM path (should be before sourcing zsh)
export NVM_LAZY_LOAD=true
export NVM_AUTO_USE=true

## Path to oh-my-zsh script
source $ZSH/oh-my-zsh.sh

## custom aliases
source $HOME/.aliases

## Setting vim as default editor
export EDITOR="vim"

## Postgres path
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin

## Adding RVM & other rails related to the path
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
export PATH="/usr/local/opt/qt@5.5/bin:$PATH"

## Yarn pkg manager path
export PATH="$HOME/.yarn/bin:$PATH"

## To set node packages path
## Allow global npm install without sudo
## Source: (https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md)
NPM_PACKAGES="${HOME}/.npm-packages"
NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
PATH="$NPM_PACKAGES/bin:$PATH"

## Unset manpath so we can inherit from /etc/manpath via the `manpath`
unset MANPATH ## delete if you already modified MANPATH elsewhere in your config
MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

## Adding z script path for easy cding...
## Source: https://github.com/rupa/z
. ~/z.sh

clear

## END
